name:                draenor
version:             1.0.0
synopsis:            Convert OSM PBF files into ORC, and upload them to S3.
description:         Convert OSM PBF files into ORC, and upload them to S3.
homepage:            https://github.com/fosskers/draenor
license:             BSD3
author:              Colin Woodbury
maintainer:          colingw@gmail.com
copyright:           2017 Azavea

extra-source-files:
  - README.md

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -Wincomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 4.11
  - aeson >= 1.1 && < 1.3
  - bytestring
  - optparse-generic >= 1.2 && < 1.3
  - shelly >= 1.6 && < 1.7
  - text

executables:
  draenor:
    source-dirs:      src
    main:             Main.hs
